### ISSUE TITLE
Discord logo missing from titlebar

### ISSUE THREAD

**Issue by piotr25691** [DiscordStyles/Slate#46]
**Describe the bug**
The discord logo is completely missing from the titlebar, other icons work.

**To Reproduce**
It happens when you install Slate by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/71488561/116780377-aa043080-aa7c-11eb-96eb-6b029f588b79.png)

**Desktop (please complete the following information):**
Discord channel: PTB
OS: Windows
Mod: BetterDiscord

**Additional context**
This can be somewhat fixed by adding this CSS:
```css
.typeWindows-1za-n7:before {
  content: '';
  position: fixed;
  background: url('https://discord.com/assets/28174a34e77bb5e5310ced9f95cb480b.png') center/cover no-repeat;
  width: 20px;
  height: 20px;
  left: 12px;
  top: 4px;
}
```
