### ISSUE TITLE
Missing emotes in replies

### ISSUE THREAD

**Issue by Lubieerror** [DiscordStyles/Slate#47]
**There's no emotes in reply menu**
**Slate (ok, I tweaked it little bit but I checked and this doesn't affect the outcome):**
![image](https://user-images.githubusercontent.com/11427815/117060868-c1b01300-ad21-11eb-8a2a-b8d24d6882e2.png)

*No theme:*
![image](https://user-images.githubusercontent.com/11427815/117062739-1c4a6e80-ad24-11eb-8153-6139852b3f14.png)

*Other theme:*
![image](https://user-images.githubusercontent.com/11427815/117060795-a5ac7180-ad21-11eb-90e7-2a87aeb77921.png)

**Setup:**
Discord channel: Stable
OS: Windows 10
Mod: BetterDiscord

**The problem disappeared after I added this at the end of my config:**
```css
#app-mount .repliedMessage-VokQwo img.replyAvatar-1K9Wmr {
  /*On screenshot it'll be display: block; since I want avatars*/
  display: none;
}

#app-mount .repliedMessage-VokQwo img.emoji {
  display: inline;
}
```

**After the fix (again just in case: avatar is visible because I wanted it):**
![image](https://user-images.githubusercontent.com/11427815/117064421-79dfba80-ad26-11eb-887d-2f26f9c66d01.png)

*I'll try to fix it on my own in pull request. I opened this issue to get you all possible information if I get stuck, forgot about it or smth else*
